version: "3.7"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: softuza/backend
    hostname: backend
    container_name: backend
    restart: always
    networks:
      default:
        ipv4_address: 172.18.1.5
    ports:
      - "3201:3201"
    healthcheck:
      test: curl --fail -s http://backend:3201/health || exit 1

networks:
  default:
    name: 2dv609