version: "3.7"
services:
  # Mysql
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.1.4
    volumes:
      - /opt/2dv609/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=testtest


networks:
  default:
    name: 2dv609
    ipam:
      config:
        - subnet: 172.18.1.0/24